trainset : 
  dataset: icdar2017
  set: train

testset : 
  dataset: icdar2017
  set: test


log_dir: /cluster/qy41tewa/rl-map/experiments
logger : wandb
train_label : cluster
addWriterEmbeddingsToTable: True
add_np_embeddingsto_table: False
rerank: True
only_test: True
test_with_np_embeddings: False

use_test_as_validation: False

# only use when train on color
grayscale : False

data_augmentation : morph

# base lr 5e-4 to 1e-5
optimizer_options: 
  optimizer: adam 
  base_lr: 0.0001 
  wd: 0 
  final_lr: 0.00001
  warmup_epochs : 5

  scheduler: const #cosine

super_fancy_new_name: icdar2017_test_5000p
#checkpoint: /cluster/qy41tewa/rl-map/experiments/icdar2017_training_5000p-2024-07-19-01-29/model.pt

model :  
    name : resnet56
    num_clusters : 100
    encoding : netvlad #netrvlad

train_options: 
  epochs: 30 
  batch_size: 1024                               
  callback : early_stopping
  callback_patience : 5

  loss : triplet  
  margin : 0.1
  sampler_m : 16
  length_before_new_iter: 512000

eval_options : 
    pca_dim : 400
    gmp_alpha : 100

test_batch_size: 512
        
