trainset : 
  dataset: icdar2017
  set: train

#valset : 
#  dataset: icdar2017
#  set: val_classify


log_dir: /cluster/qy41tewa/rl-map/experiments
logger : wandb
train_label : writer

use_test_as_validation: False

# only use when train on color
grayscale : False

# data_augmentation : morph

# base lr 5e-4 to 1e-5
optimizer_options: 
  optimizer: adam 
  base_lr: 0.00001
  wd: 0 
  final_lr: 0.0001
  warmup_epochs : 5

super_fancy_new_name: icdar2017_classifier_training_batch1024_sampler_m64

model :  
    name : resnet56
    num_clusters : 100
    encoding : netrvlad

classifier :  
    num_writers : 394

train_options: 
  epochs: 80
  batch_size: 1024                               
  callback : early_stopping
  callback_patience : 5

  loss : crossentropyloss  
  margin : 0.1
  sampler_m : 16
  length_before_new_iter: 512000

eval_options : 
    pca_dim : 400
    gmp_alpha : 100

test_batch_size: 256
        
