trainset : 
  dataset: icdar2019_color
  set: train

testset : 
  dataset: icdar2019_color
  set: test


log_dir: /cluster/qy41tewa/rl-map/experiments
logger : wandb
train_label : writer

test: True
train: True
plot_emb: False
checkpoint: /cluster/qy41tewa/rl-map/experiments/base_netvlad_model/model.pt

# only use when train on color
grayscale : True

data_augmentation : morph

# base lr 5e-6 to 1e-6
optimizer_options: 
  optimizer: adam 
  base_lr: 0.000001
  wd: 0 
  final_lr: 0.000001
  warmup_epochs : 3

super_fancy_new_name: icdar19_color_rewardfinetuning_from_icdar17_embeddings

model :  
    name : resnet56
    num_clusters : 100
    encoding : netrvlad

train_options: 
  epochs: 30 
  batch_size: 1024                               
  callback : early_stopping
  callback_patience : 5

  loss : triplet  
  margin : 0.1
  sampler_m : 16
  length_before_new_iter: 512000

eval_options : 
    pca_dim : 400
    gmp_alpha : 100

test_batch_size: 512
        